.TH BIBLEDIT 1 "January 24 2017" "Version 1.0"
.SH NAME
.B bibledit \- Bibledit
.SH DESCRIPTION
Bibledit is a Bible editor.
Type "bibledit" in a terminal to start it.
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
