.TH BIBLEDIT-CLOUD 1 "May 27 2017" "Version 5.0"
.SH NAME
.B bibledit-cloud \- Bibledit Cloud server
.SH DESCRIPTION
Bibledit-Cloud is an online Bible editor.
Type "bibledit-cloud" in a terminal to start it.
Point a browser at http://localhost:8080 to open the
graphical user interface.
For more information see the graphical user interface.
.PP
.SH LICENSE
This program is distributed under the GNU General Public License, as noted in
each source file.
