#!/bin/bash

echo Build everything
make --jobs=10
if [ $? -ne 0 ]; then exit; fi

echo Copy everything to working location
rsync -av --exclude=libbibledit.a . ~/work/bibledit/dev
if [ $? -ne 0 ]; then exit; fi

echo Start bibledit
cd ~/work/bibledit/dev
if [ $? -ne 0 ]; then exit; fi
./server

