#!/bin/bash

echo Run this script to sync all files to a temporary location.
echo Then run bibledit in that location.
echo This ensures that no databases are being created in the source tree.
watch -n 1 "rsync -av --exclude=libbibledit.a . /tmp/bibledit-dev"


