Sender: bibledit-general@googlegroups.com
MIME-Version: 1.0
From: Sender <sender@domain.net>
Date: Wed, 15 Mar 2017 14:20:57 +0900
Subject: Message encoded in base64
To: bibledit-general@googlegroups.com
Content-Type: multipart/alternative; boundary=001a11472176307118054abe1cc9

--001a11472176307118054abe1cc9
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

SW4gdGhlIGJlZ2lubmluZyBHb2QgY3JlYXRlZCB0aGUgaGVhdmVuIGFuZCB0aGUgZWFydGguDQrXkda81rDXqNa115DXqdeB1rTXmdeqLCDXkda81rjXqNa415Ag15DWsdec1rnXlNa015nXnSwg15DWtdeqINeU1rfXqda814HWuNee1rfXmda0150sINeV1rDXkNa116og15TWuNeQ1rjXqNa216Uu

--001a11472176307118054abe1cc9
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div>text</div>

--001a11472176307118054abe1cc9--
