/*
Copyright (©) 2003-2025 Teus Benschop.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/


#pragma once

constexpr const char* usfm_with_all_markers =
R"(\id GEN)" "\n"
R"(\ide UTF-8)" "\n"
R"(\sts Released)" "\n"
R"(\usfm 3.0)" "\n"
R"(\rem Remark)" "\n"
R"(\h Genesis)" "\n"
R"(\h1 Genesis)" "\n"
R"(\h2 Left)" "\n"
R"(\h3 Right)" "\n"
R"(\toc1 The book of Genesis)" "\n"
R"(\toc2 Genesis)" "\n"
R"(\toc3 Gen.)" "\n"
R"(\mt Major title)" "\n"
R"(\mt1 Major title 1)" "\n"
R"(\mt2 Major title 2)" "\n"
R"(\mt3 Major title 3)" "\n"
R"(\mt4 Major title 4)" "\n"
R"(\mte Major title at ending)" "\n"
R"(\mte1 Major title at ending 1)" "\n"
R"(\mte2 Major title at ending 2)" "\n"
R"(\ms Major section heading)" "\n"
R"(\ms1 Major section heading 1)" "\n"
R"(\ms2 Major section heading 2)" "\n"
R"(\mr Major section references)" "\n"
R"(\s Section heading)" "\n"
R"(\s1 Section heading 1)" "\n"
R"(\s2 Section heading 2)" "\n"
R"(\s3 Section heading 3)" "\n"
R"(\s4 Section heading 4)" "\n"
R"(\sr Section references)" "\n"
R"(\r Parallel passage references)" "\n"
R"(\rq Inline quotation references\rq*)" "\n"
R"(\d Descriptive title)" "\n"
R"(\sp Speaker)" "\n"
R"(\sd Semantic division)" "\n"
R"(\sd1 Semantic division 1)" "\n"
R"(\sd2 Semantic division 2)" "\n"
R"(\sd3 Semantic division 3)" "\n"
R"(\sd4 Semantic division 4)" "\n"
R"(\imt Main Title)" "\n"
R"(\imt1 Main Title 1)" "\n"
R"(\imt2 Main Title 2)" "\n"
R"(\imt3 Main Title 3)" "\n"
R"(\imt4 Main Title 4)" "\n"
R"(\is Section)" "\n"
R"(\is1 Section 1)" "\n"
R"(\is2 Section 2)" "\n"
R"(\ip Introduction paragraph)" "\n"
R"(\ipi Introduction paragraph indented)" "\n"
R"(\im Introduction margin paragraph)" "\n"
R"(\imi Introduction margin paragraph indented)" "\n"
R"(\ipq Introduction paragraph quote)" "\n"
R"(\imq Introduction margin paragraph quote)" "\n"
R"(\ipr Introduction paragraph right)" "\n"
R"(\iq Introduction poetry)" "\n"
R"(\iq1 Introduction poetry 1)" "\n"
R"(\iq2 Introduction poetry 2)" "\n"
R"(\iq3 Introduction poetry 3)" "\n"
R"(\ib)" "\n"
R"(\ili 1 Introduction list item)" "\n"
R"(\ili1 1 Introduction list item 1)" "\n"
R"(\ili2 1 Introduction list item 2)" "\n"
R"(\iot Introduction Outline Title)" "\n"
R"(\io Introduction outline)" "\n"
R"(\io1 Introduction outline 1)" "\n"
R"(\io2 Introduction outline 2)" "\n"
R"(\io3 Introduction outline 3 \ior references\ior*)" "\n"
R"(\io4 Introduction outline 4 \iqt quotation\iqt*)" "\n"
R"(\iex Introduction explanatory text)" "\n"
R"(\imte Introduction main title ending)" "\n"
R"(\imte1 Introduction main title ending 1)" "\n"
R"(\imte2 Introduction main title ending 2)" "\n"
R"(\ie)" "\n"
R"(\c 1)" "\n"
R"(\ca 2\ca*)" "\n"
R"(\p)" "\n"
R"(\v 1 \vp 1b\vp* Text name\pro pronunciation\pro*.)" "\n"
R"(\c 2)" "\n"
R"(\cl Psalm)" "\n"
R"(\p)" "\n"
R"(\v 1 Normal \add added\add* and \addpn AddPn\addpn*)" "\n"
R"(\c 3)" "\n"
R"(\cp א)" "\n"
R"(\p)" "\n"
R"(\v 1 Verse text)" "\n"

R"(\c 4)" "\n"
R"(\cd Chapter description)" "\n"
R"(\m Continuation (margin) paragraph.)" "\n"
R"(\po Paragraph opening an epistle.)" "\n"
R"(\pr Right aligned paragraph.)" "\n"
R"(\cls Closure of letter.)" "\n"
R"(\pmo Embedded text opening.)" "\n"
R"(\pm Embedded text paragraph.)" "\n"
R"(\pmc Embedded text closing.)" "\n"
R"(\pmr Embedded text refrain.)" "\n"
R"(\pi Indented paragraph.)" "\n"
R"(\pi1 Indented paragraph 1.)" "\n"
R"(\pi2 Indented paragraph 2.)" "\n"
R"(\pi3 Indented paragraph 3.)" "\n"
R"(\mi Margin indented.)" "\n"
R"(\nb No break.)" "\n"
R"(\pc Centred paragraph.)" "\n"
R"(\ph Hanging paragraph.)" "\n"
R"(\ph1 Hanging paragraph 1.)" "\n"
R"(\ph2 Hanging paragraph 2.)" "\n"
R"(\ph3 Hanging paragraph 3.)" "\n"
R"(\ph4 Hanging paragraph 4.)" "\n"
R"(\b)" "\n"
R"(\q Poetic line.)" "\n"
R"(\q1 Poetic line 1.)" "\n"
R"(\q2 Poetic line 2.)" "\n"
R"(\q3 Poetic line 3.)" "\n"
R"(\qr Right-aligned poetic line)" "\n"
R"(\qc Centered poetic line)" "\n"
R"(\q Poetry \qs Selah\qs*)" "\n"
R"(\qa Aleph)" "\n"
R"(\p \qac A\qac*rostic)" "\n"
R"(\qm Embedded poetic line)" "\n"
R"(\qm1 Embedded poetic line 1)" "\n"
R"(\qm2 Embedded poetic line 2)" "\n"
R"(\qm3 Embedded poetic line 3)" "\n"
R"(\qd Hebrew note)" "\n"
R"(\lh List header)" "\n"
R"(\li List item)" "\n"
R"(\li1 List item 1)" "\n"
R"(\li2 List item 2)" "\n"
R"(\li3 List item 3)" "\n"
R"(\li4 List item 4)" "\n"
R"(\lf List footer)" "\n"
R"(\lim Embedded list item)" "\n"
R"(\lim1 Embedded list item 1)" "\n"
R"(\lim2 Embedded list item 2)" "\n"
R"(\p List \litl total\litl*)" "\n"
R"(\li \lik Key\lik* \liv Value\liv* \liv1 Value 1\liv1* \liv2 Value 2\liv2*)" "\n"

R"(\c 5)" "\n"
R"(\p)" "\n"
R"(\v 1 The table:)" "\n"
R"(\tr \th1 Column1\th2 Column2\th3 Column3\th4 Column4)" "\n"
R"(\tr \thr1 R-Column1\thr2 R-Column2\thr3 R-Column3\thr4 R-Column4)" "\n"
R"(\tr \tc1 Cell1\tc2 Cell2\tc3 Cell3\tc4 Cell4)" "\n"
R"(\tr \tcr1 R-Cell1\tcr2 R-Cell2\tcr3 R-Cell3\tcr4 R-Cell4)" "\n"

R"(\c 6)" "\n"
R"(\p text\f + \fr ref \ft note \fq quote \fv 3\fv* \fqa alternate quote \fk keyword \fl label \fw witness \fdc deuterocanonical\fdc* \fm mark\fm*\f*)" "\n"
R"(\p text\fe + \fr ref\ft note\fe*)" "\n"
R"(\p text\ef + \fr ref\ft note\ef*)" "\n"
R"(\p text\f + \fp paragraph\f*)" "\n"
R"(\p text\x + \xo origin \xk keyword \xq quotation \xt targets \xta added \xop published\xop* \xot old testament\xot* \xnt new testament\xnt* \xdc deuterocanonical\xdc*\x*)" "\n"
R"(\p text\ex + \xt targets\ex*)" "\n"

R"(\p The \bk Book\bk* name)" "\n"
R"(\p Proto \dc Deutero\dc* text.)" "\n"
R"(\p This is a \k keyword\k*)" "\n"
R"(\p \nd Yahweh\nd*)" "\n"
R"(\p The 1\ord st\ord*.)" "\n"
R"(\p It is about \pn Jesus\pn*.)" "\n"
R"(\p The capital is \png Amsterdam\png*.)" "\n"
R"(\p This is a \qt quotation\qt*.)" "\n"
R"(\p \sig Kind regards from Paul\sig*.)" "\n"
R"(\p Hebrew and \sls Aramaic\sls* source.)" "\n"
R"(\p Jesus: \tl Eli, Eli, lema sabachthani?\tl*)" "\n"
R"(\p Jesus: \wj I am\wj*.)" "\n"
R"(\p This is \em emphasized\em* text.)" "\n"
R"(\p This is \bd bold\bd* text.)" "\n"
R"(\p This is \it italic\it* text.)" "\n"
R"(\p This is \bdit bold/italic\bdit* text.)" "\n"
R"(\s Section heading with \no normal\no* text)" "\n"
R"(\p This is \sc small cap\sc* text.)" "\n"
R"(\p This is \sup superscript\sup* text.)" "\n"
R"(\lit Liturgical note)" "\n"
R"(\pb)" "\n"
R"(\c 7)" "\n"
R"(\p This chapter is on a new page)" "\n"
R"(\c 8)" "\n"
R"(\p Text)" "\n"
R"(\fig caption|src="image.png" size="size" ref="reference"\fig*)" "\n"
R"(\p Text)" "\n"
R"(\fig DESC|FILE|SIZE|LOC|COPY|CAP|REF\fig*)" "\n"
R"(\p \ndx index\ndx* \w word\w* \wg greek\wg* \wh hebrew\wh* \wa aramaic\wa*)" "\n"
R"(\p Text\rb wd|"gloss:gloss"\rb*)" "\n"
R"(\esb)" "\n"
R"(\p Sidebar)" "\n"
R"(\esbe)" "\n"
//R"(\esb \cat category\cat*)" "\n"
R"(\esb)" "\n"
R"(\p text\ef - \cat category\cat* \ft note\ef*)" "\n"
R"(\esbe)" "\n"

;
